package walshe.projectcolumbo.persistence.model;

public enum TrendState {
    SUPERTREND_BULLISH,
    SUPERTREND_BEARISH,
    SUPERTREND_UNKNOWN,
    RSI_ABOVE_60,
    RSI_BELOW_40,
    RSI_NEUTRAL,
    ELDER_IMPULSE_GREEN,
    ELDER_IMPULSE_RED,
    ELDER_IMPULSE_NEUTRAL,
    ELDER_THERMOMETER_QUIET,
    ELDER_THERMOMETER_HOT,
    ELDER_THERMOMETER_SPIKE
}
