spring:
  application:
    name: project-columbo

  datasource:
    url: jdbc:postgresql://localhost:5432/mydatabase
    username: myuser
    password: secret

  jpa:
    hibernate:
      ddl-auto: validate
    open-in-view: false

  flyway:
    enabled: true

logging:
  level:
    org.flywaydb: DEBUG
    org.springframework.jdbc: INFO


