-- V11 Migration: Ensure all 60 requested assets exist
-- Inserts all symbols provided by the user, idempotently.

INSERT INTO asset (symbol, provider, active, created_at)
VALUES
  ('BTC', 'BINANCE', true, now()),
  ('ETH', 'BINANCE', true, now()),
  ('XRP', 'BINANCE', true, now()),
  ('BNB', 'BINANCE', true, now()),
  ('SOL', 'BINANCE', true, now()),
  ('TRX', 'BINANCE', true, now()),
  ('DOGE', 'BINANCE', true, now()),
  ('ADA', 'BINANCE', true, now()),
  ('WBT', 'BINANCE', true, now()),
  ('BCH', 'BINANCE', true, now()),
  ('LEO', 'BINANCE', true, now()),
  ('HYPE', 'BINANCE', true, now()),
  ('LINK', 'BINANCE', true, now()),
  ('CC', 'BINANCE', true, now()),
  ('XMR', 'BINANCE', true, now()),
  ('XLM', 'BINANCE', true, now()),
  ('RAIN', 'BINANCE', true, now()),
  ('HBAR', 'BINANCE', true, now()),
  ('LTC', 'BINANCE', true, now()),
  ('DAI', 'BINANCE', true, now()),
  ('ZEC', 'BINANCE', true, now()),
  ('AVAX', 'BINANCE', true, now()),
  ('SUI', 'BINANCE', true, now()),
  ('SHIB', 'BINANCE', true, now()),
  ('CRO', 'BINANCE', true, now()),
  ('WLFI', 'BINANCE', true, now()),
  ('TON', 'BINANCE', true, now()),
  ('DOT', 'BINANCE', true, now()),
  ('XAUT', 'BINANCE', true, now()),
  ('UNI', 'BINANCE', true, now()),
  ('PAXG', 'BINANCE', true, now()),
  ('M', 'BINANCE', true, now()),
  ('MNT', 'BINANCE', true, now()),
  ('AAVE', 'BINANCE', true, now()),
  ('TAO', 'BINANCE', true, now()),
  ('PEPE', 'BINANCE', true, now()),
  ('ASTER', 'BINANCE', true, now()),
  ('OKB', 'BINANCE', true, now()),
  ('BGB', 'BINANCE', true, now()),
  ('NEAR', 'BINANCE', true, now()),
  ('HTX', 'BINANCE', true, now()),
  ('ETC', 'BINANCE', true, now()),
  ('ONDO', 'BINANCE', true, now()),
  ('ICP', 'BINANCE', true, now()),
  ('POL', 'BINANCE', true, now()),
  ('WLD', 'BINANCE', true, now()),
  ('KCS', 'BINANCE', true, now()),
  ('GT', 'BINANCE', true, now()),
  ('PUMP', 'BINANCE', true, now()),
  ('NIGHT', 'BINANCE', true, now()),
  ('ATOM', 'BINANCE', true, now()),
  ('QNT', 'BINANCE', true, now()),
  ('ENA', 'BINANCE', true, now()),
  ('NEXO', 'BINANCE', true, now()),
  ('KAS', 'BINANCE', true, now()),
  ('FLR', 'BINANCE', true, now()),
  ('TRUMP', 'BINANCE', true, now()),
  ('ALGO', 'BINANCE', true, now()),
  ('FIL', 'BINANCE', true, now()),
  ('RENDER', 'BINANCE', true, now())
ON CONFLICT (symbol, provider) DO NOTHING;
