-- 118 assets sourced from MEXC's public spot API (crypto directly; tokenized real-equity
-- STOCK/ETF pairs via the Ondo "-ON" wrapper), replacing Binance and Tiingo as the active data
-- source - see openspec/changes/migrate-to-mexc-provider/design.md and asset-list.md for the full
-- derivation (top-100-by-market-cap source lists, live-matched against MEXC, capped at the top 50
-- tradeable names by rank for CRYPTO/STOCK; ETF's 18 matches stay uncapped).
--
-- GOOGLONUSDT substitutes for the requested GOOG (Class C) - MEXC only wraps Alphabet's Class A.
-- venue and name are set explicitly on every row, matching V17's established convention (not
-- V12's original mistake of relying on venue's DEFAULT).
--
-- Deactivating BINANCE/TIINGO happens in a later migration (after this one), not here, so no
-- asset class ever has zero active assets mid-migration.
INSERT INTO asset (symbol, provider, active, asset_class, venue, name, created_at)
VALUES
    ('BTCUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Bitcoin', now()),
    ('ETHUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Ethereum', now()),
    ('BNBUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'BNB', now()),
    ('XRPUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'XRP', now()),
    ('SOLUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Solana', now()),
    ('TRXUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'TRON', now()),
    ('HYPEUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Hyperliquid', now()),
    ('DOGEUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Dogecoin', now()),
    ('ZECUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Zcash', now()),
    ('WBTUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'WhiteBIT Coin', now()),
    ('LINKUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Chainlink', now()),
    ('XMRUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Monero', now()),
    ('ADAUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Cardano', now()),
    ('XLMUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Stellar', now()),
    ('BCHUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Bitcoin Cash', now()),
    ('CCUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Canton', now()),
    ('GRAMUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Gram (prev. Toncoin)', now()),
    ('LTCUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Litecoin', now()),
    ('HBARUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Hedera', now()),
    ('AVAXUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Avalanche', now()),
    ('SHIBUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Shiba Inu', now()),
    ('SUIUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Sui', now()),
    ('CROUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Cronos', now()),
    ('UNIUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Uniswap', now()),
    ('MUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'MemeCore', now()),
    ('NEARUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'NEAR Protocol', now()),
    ('OKBUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'OKB', now()),
    ('TAOUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Bittensor', now()),
    ('AAVEUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Aave', now()),
    ('ASTERUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Aster', now()),
    ('WLFIUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'World Liberty Financial', now()),
    ('ONDOUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Ondo', now()),
    ('PUMPUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Pump.fun', now()),
    ('MNTUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Mantle', now()),
    ('MORPHOUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Morpho', now()),
    ('PEPEUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Pepe', now()),
    ('SKYUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Sky', now()),
    ('HTXUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'HTX DAO', now()),
    ('DOTUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Polkadot', now()),
    ('WLDUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Worldcoin', now()),
    ('ENAUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Ethena', now()),
    ('ICPUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Internet Computer', now()),
    ('BGBUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Bitget Token', now()),
    ('POLUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'POL (ex-MATIC)', now()),
    ('UUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'United Stables', now()),
    ('ETCUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Ethereum Classic', now()),
    ('BTWUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Bitway', now()),
    ('PIUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Pi Network', now()),
    ('KCSUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'KuCoin', now()),
    ('QNTUSDT', 'MEXC', true, 'CRYPTO', 'MEXC', 'Quant', now()),
    ('NVDAONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'NVIDIA', now()),
    ('AAPLONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Apple', now()),
    ('GOOGLONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Alphabet Class A', now()),
    ('MSFTONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Microsoft', now()),
    ('AMZNONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Amazon', now()),
    ('TSMONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Taiwan Semiconductor', now()),
    ('SPCXONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'SpaceX', now()),
    ('AVGOONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Broadcom', now()),
    ('METAONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Meta Platforms', now()),
    ('TSLAONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Tesla', now()),
    ('LLYONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Eli Lilly', now()),
    ('MUONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Micron Technology', now()),
    ('JPMONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'JPMorgan Chase', now()),
    ('SKHYONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'SK hynix', now()),
    ('WMTONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Walmart', now()),
    ('AMDONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'AMD', now()),
    ('VONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Visa', now()),
    ('ASMLONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'ASML Holding', now()),
    ('XOMONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Exxon Mobil', now()),
    ('JNJONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Johnson & Johnson', now()),
    ('MAONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Mastercard', now()),
    ('ABBVONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'AbbVie', now()),
    ('INTCONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Intel', now()),
    ('CSCOONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Cisco Systems', now()),
    ('BACONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Bank of America', now()),
    ('COSTONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Costco', now()),
    ('ORCLONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Oracle', now()),
    ('PLTRONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Palantir', now()),
    ('CVXONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Chevron', now()),
    ('KOONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Coca-Cola', now()),
    ('LRCXONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Lam Research', now()),
    ('MRKONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Merck', now()),
    ('AMATONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Applied Materials', now()),
    ('CATONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Caterpillar', now()),
    ('GEONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'GE Aerospace', now()),
    ('UNHONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'UnitedHealth', now()),
    ('NFLXONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Netflix', now()),
    ('PGONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Procter & Gamble', now()),
    ('GSONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Goldman Sachs', now()),
    ('DELLONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Dell Technologies', now()),
    ('RTXONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'RTX', now()),
    ('BABAONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Alibaba', now()),
    ('PANWONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Palo Alto Networks', now()),
    ('ARMONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Arm Holdings', now()),
    ('WFCONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Wells Fargo', now()),
    ('SAPONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'SAP', now()),
    ('GEVONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'GE Vernova', now()),
    ('ANETONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Arista Networks', now()),
    ('KLACONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'KLA', now()),
    ('AMGNONUSDT', 'MEXC', true, 'STOCK', 'MEXC', 'Amgen', now()),
    ('IVVONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Core S&P 500 ETF', now()),
    ('SPYONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'SPDR S&P 500 ETF', now()),
    ('QQQONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'Invesco QQQ Trust', now()),
    ('IEFAONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Core MSCI EAFE ETF', now()),
    ('IEMGONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Core MSCI Emerging Markets ETF', now()),
    ('GLDONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'SPDR Gold Shares', now()),
    ('AGGONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Core U.S. Aggregate Bond ETF', now()),
    ('IJHONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Core S&P Mid-Cap ETF', now()),
    ('IWFONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Russell 1000 Growth ETF', now()),
    ('SGOVONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares 0-3 Month Treasury Bond ETF', now()),
    ('ITOTONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Core S&P Total U.S. Stock Market ETF', now()),
    ('IWMONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Russell 2000 ETF', now()),
    ('EFAONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares MSCI EAFE ETF', now()),
    ('IAUONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Gold Trust', now()),
    ('TLTONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares 20+ Year Treasury Bond ETF', now()),
    ('SOXXONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Semiconductor ETF', now()),
    ('TQQQONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'ProShares UltraPro QQQ', now()),
    ('SLVONUSDT', 'MEXC', true, 'ETF', 'MEXC', 'iShares Silver Trust', now());
